/**
 * Lista de ciudades de Colombia para sugerencias en formularios (capitales de departamento
 * y ciudades principales). El usuario puede elegir de la lista o escribir manualmente.
 */
export const CIUDADES_COLOMBIA: string[] = [
  "Armenia",
  "Barranquilla",
  "Bogotá",
  "Bucaramanga",
  "Cali",
  "Cartagena",
  "Chía",
  "Cúcuta",
  "Floridablanca",
  "Fusagasugá",
  "Girardot",
  "Ibagué",
  "Manizales",
  "Medellín",
  "Montería",
  "Neiva",
  "Palmira",
  "Pasto",
  "Pereira",
  "Popayán",
  "Santa Marta",
  "Sincelejo",
  "Soacha",
  "Tunja",
  "Valledupar",
  "Villavicencio",
  "Zipaquirá",
  // Capitales adicionales
  "Arauca",
  "Florencia",
  "Leticia",
  "Mocoa",
  "Mitú",
  "Puerto Carreño",
  "Puerto Inírida",
  "Quibdó",
  "Riohacha",
  "San Andrés",
  "San José del Guaviare",
  "Yopal",
]
